# Generated by Django 3.2.2 on 2022-05-22 02:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markitten_app', '0003_auto_20220522_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birthday',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
