# Generated by Django 4.0.4 on 2022-05-24 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markitten_app', '0005_auto_20220523_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='office_email',
            field=models.CharField(default='abcd@gmail.com', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='personal_email',
            field=models.CharField(default='abcd@gmail.com', max_length=100),
        ),
    ]
