# Generated by Django 4.0.4 on 2022-05-25 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markitten_app', '0006_profile_office_email_profile_personal_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={'managed': False},
        ),
    ]
