# Generated by Django 4.0.4 on 2022-05-25 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markitten_app', '0011_remove_proddetails_quantity_profile_office_email_and_more'),
    ]

    operations = [
    ]
