# Generated by Django 4.0.4 on 2022-05-31 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markitten_app', '0013_alter_comment_options_profile_office_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='description',
            new_name='complaint',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='imageReview',
        ),
    ]
