# Generated by Django 4.0.4 on 2022-05-31 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markitten_app', '0014_rename_description_complaint_complaint_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='complaint',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='subject',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterModelTable(
            name='complaint',
            table='Complaints',
        ),
    ]
