# Generated by Django 4.0.4 on 2022-05-31 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markitten_app', '0015_profile_office_email_profile_personal_email_and_more'),
    ]

    operations = [
    ]
