# Generated by Django 4.0.4 on 2022-05-31 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markitten_app', '0016_profile_office_email_profile_personal_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Complaint',
        ),
    ]
